### ISSUE TITLE
Update component location in Wiki

### ISSUE THREAD

**Issue by mattsaxon** [beveradb/sonoff-lan-mode-homeassistant#51]
Great work Andrew, I've just started using your component.

This is just a minor issue with the wiki that it suggest to install the component in a deprecated directory, the location is still working for me (version 90.1), but an error in the log suggests it will stop working soon.

The location to put the script should be "custom_components/sonoff_lan_mode/switch.py" (so a rename of directory and a rename of the script itself.

If nothing else it will keep logs a bit cleaner and help identify other issues.

Great work again and when I get a bit more advanced with understanding home assistant, I may be in a position to help with this component too if necessary.

**Comment by beveradb** [comment]
Thanks for the heads up!

Does this look right? https://github.com/beveradb/sonoff-lan-mode-homeassistant/pull/53

**Comment by mattsaxon** [comment]
Yes, PR looks good to me.
