### ISSUE TITLE
Wrong Custom component location ??

### ISSUE THREAD

**Issue by max-rh** [beveradb/sonoff-lan-mode-homeassistant#69]
Hello there,
Thanks for the amazing work, was looking for something like this for a long time.

When i placed the component in the custom_components directory HA didn't recognize it `"Integration sonoff_lan_mode not found when trying to verify its switch platform."`

Note: I already have other custom_components within the directory and they work fine.

Any Advice?

Thanks

**Comment by mattsaxon** [comment]
I have a manifest.json in the same directory which fixed this for me, its part of this PR https://github.com/beveradb/sonoff-lan-mode-homeassistant/pull/65.

**Comment by mattsaxon** [comment]
@max-rh, can you confirm that this worked for you too.

**Comment by mattsaxon** [comment]
I have updated the readme to state that manifest.json needs to be in the folder too.

Closing, please reopen if this is still a problem
